GET /articles/_search HTTP/1.1
Host: {{host}}
Content-Type: application/json
//GET http://localhost:9200/articles/_search?q=content-part:keyword1 AND content-part:keyword2

{
  "query":
    { "bool" :
          {
             "must":[
                        {"term": {"content-part": "{{keyword1}}" } },
                        {"term": {"content-part": "{{keyword2}}" } }
                    ]
          }
    }
}